import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import "./theme.css";
import Navbar from "@/components/Navbar";
import { CartProvider } from "@/app/contexts/CartContext";
import { ThemeProvider } from "@/app/contexts/ThemeContext";
import PageTransition from "@/components/PageTransition";
import { SessionProvider } from "next-auth/react";

const primaryFont = Geist({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cosmic Site",
  description: "Generated by Cosmic",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={primaryFont.className}>
      <body className="antialiased  text-foreground">
        {/* Early theme application to avoid flash */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
              try {
                const saved = localStorage.getItem('eliteshop-theme');  
                const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;  
                const theme =
                  saved === 'light' || saved === 'dark'
                    ? saved
                    : (prefersDark ? 'dark' : 'light'); 
                document.documentElement.setAttribute('data-theme', theme);  
              } catch(_) {}
            })();`,
          }}
        />
        <ThemeProvider>
        <SessionProvider>
          <CartProvider>
            <Navbar />
            <main className="min-h-screen pt-16 bg-background">
              <PageTransition>{children}</PageTransition>
            </main>
          </CartProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
